---
- hosts: theone
  become: yes
  vars_files:
    - vars.yaml

  tasks:
    - name: install repo for PostgreSQL
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: " install PostgreSQL version {{ postgresql_version }}"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
          - "postgresql{{ postgresql_version }}-server"
          - python-psycopg2

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "{{ postgresql_config_path }}/pg_hba.conf"
      register: postgres_data

    - name: Initialize Postgres
      command: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service:
        name: "postgresql-{{ postgresql_version }}"
        state: started
        enabled: yes

    - name: "Create database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: "{{ postgresql_user }}"

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: "{{ postgresql_user }}"

    - name: "Grant the user full access to the new database"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: "{{ postgresql_user }}"

    - name: Configure host based authentication (if entries are configured).
      template:
        src: "pg_hba.conf.j2"
        dest: "{{ postgresql_config_path }}/pg_hba.conf"
        owner: "{{ postgresql_user }}"
        group: "{{ postgresql_group }}"
        mode: 0600
      notify: restart postgres

  handlers:
    - name: restart postgres
      service: "name=postgresql-{{ postgresql_version }} state=restarted"
      
