---
- name: Check for existing binary
  stat:
    path: "{{ minio_binary_dir }}/minio"
  register: minio_binary_stat_result

- name: Download minio server
  get_url:
    url: "{{ minio_download_url }}"
    dest: "{{ minio_download_dir }}"
    mode: 0755
  when: minio_always_update_binary or not minio_binary_stat_result.stat.exists

- name: Install minio binary
  copy:
    src: "{{ minio_download_dir }}/minio"
    dest: "{{ minio_binary_dir }}/minio"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755
    remote_src: true
    force: "{{ minio_always_update_binary }}"
  when: minio_always_update_binary or not minio_binary_stat_result.stat.exists

- name: Change file ownership, group and permissions
  file:
    path: "{{ mount_file }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755

- name: Creates configurations directory
  file:
    path: "{{ minio_conf_dir }}"
    state: directory

- name: Create minio configurations file.
  template:
      src: "minio.conf.j2"
      dest: "{{ minio_conf_dir }}/minio.conf"
      owner: "{{ minio_user }}"
      group: "{{ minio_group }}"
      mode: 0755

- name: Create minio service file.
  template:
      src: "minio.service.j2"
      dest: "{{ minio_service_dir }}/minio.service"
      owner: root
      group: root
      mode: 0644

- name: "Start and enable services"
  service:
      name: minio
      state: started
      enabled: yes


  